security:
    encoders:
        App\Entity\User:
            algorithm: argon2i
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        signup:
            pattern: ^/api/users
            stateless: true
            anonymous: true
            methods: [POST]
        authentication:
            pattern: ^/api/authentication_token
            stateless: true
            anonymous: true
        api:
            pattern: ^/api
            stateless: true
            anonymous: true
    access_control:
        - {
              path: ^/api/authentication_token,
              roles: IS_AUTHENTICATED_ANONYMOUSLY,
          }
        - {
              path: ^/api/users,
              roles: IS_AUTHENTICATED_FULLY,
              methods: [GET, PUT, PATCH, DELETE],
          }
