vich_uploader:
    db_driver: orm

    mappings:
        user_avatar:
            uri_prefix: /img/users
            upload_destination: "%kernel.project_dir%/public/img/users"
            namer: Vich\UploaderBundle\Naming\UniqidNamer
